### ISSUE TITLE
Error after update to v11

### ISSUE THREAD

**Issue by derekbarnett** [zarmstrong/pfs-consumables#2]
When I update modules, I'm getting an error with the description "Error: Module validation errors: packs: 0: type may not be undefined" after having updated to v11.

**Comment by benyar** [comment]
If you're comfortable editing module.json, you can fix this.
Under the section that starts with "Version", change `"maximum"` to 11

Under the section that starts with `"packs"`
add a new line (I put it right below `"system"`
That line should read:
`"type": "JournalEntry",`

That should fix it.  I've tested this in a local installation and a Forge installation.

**Comment by zarmstrong** [comment]
> If you're comfortable editing module.json, you can fix this. Under the section that starts with "Version", change `"maximum"` to 11
> 
> Under the section that starts with `"packs"` add a new line (I put it right below `"system"`) That line should read: `"type": "JournalEntry",`
> 
> That should fix it. I've tested this in a local installation and a Forge installation.

Cna you submit a pull request? Life's been very busy and I haven't updated to 11 or had time to test yet, but happy to merge your change!

**Comment by benyar** [comment]
Never done that, but I'll try.  I just hacked on this.

**Comment by benyar** [comment]
Done, although I just hacked on version numbers to make them different and you may want to review.  Your project, I just fumbled into a solution.

**Comment by derekbarnett** [comment]
Oddly, I had `"type": "JournalEntry",` in there already. Changing the version number did allow it to load up and work in v11 for me, but I'm still getting that error.

Edit: maybe this error is popping up when trying to update rather than loading. I'm not entirely certain how to tell but when I load up the world, I'm not seeing an error in that console. Only seeing it on the update page.

Edit 2: I've got quite a few formatting differences between my module.json and the one here on git . Not entirely certain what to make of it. It doesn't appear to be malicious or anything, all the versions, urls and such match, just some formatting differences. I suppose it's possible that I gave it a direct url that I just grabbed from post somewhere to install but as a rule I install directly through foundry. I'll investigate further, see if I can figure out where mine came from. If you want to see it, let me know and I'll attach it.

**Comment by benyar** [comment]
I failed to mention removing the '.db' from "pfsconsumables" but that's
another step.  v11 changed the database format and removing the file
extension is necessary for Foundry to do the database conversion.

I don't know if that solves your error, and I'm no programmer, but I've
lucked upon it somehow.

**Comment by benyar** [comment]
I'm no longer confident in my solution.  I was able to make this work for myself, but for some reason my players couldn't see it today.  If I was wrong I apologize.
